# Generated by Django 3.2.10 on 2021-12-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pk',), 'verbose_name': 'ordem de compra',
                     'verbose_name_plural': 'ordens de compra'},
        ),
    ]
