# Generated by Django 3.2.10 on 2021-12-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nf',
            field=models.CharField(max_length=7, unique=True, verbose_name='nota fiscal'),
        ),
    ]
