# Generated by Django 3.2.15 on 2022-10-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_provider'),
        ('ecommerce', '0003_alter_order_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='product.provider'),
        ),
    ]
